name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: ${{ matrix.node-version }}

      - name: Turborepo cache
        uses: actions/cache@v2
        with:
          path: .turbo/cache
          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ github.sha }}-${{ github.workflow }}-${{ github.job }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ github.sha }}-${{ github.workflow }}-
            ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ github.sha }}-
            ${{ runner.os }}-${{ matrix.node-version }}-yarn-

      - name: Linting cache
        uses: actions/cache@v2
        with:
          path: '**/.eslintcache'
          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Check types
        run: yarn typecheck

      - name: Check formatting
        run: yarn lint

      - name: Check formatting
        run: yarn test
